### ISSUE TITLE
delay(200);   IR

### ISSUE THREAD

**Issue by Wyatt59** [d7prog/Internet-Radio#1]
Hello 
You can use something like this :

unsigned long previousMillis = 0;
const long interval = 200; 

void loop() {

  unsigned long currentMillis = millis();

  if (currentMillis - previousMillis >= interval) {
      previousMillis = currentMillis;
}

you can look for somthing like "arduino how to replace delay()"

and  audioeth.loop();  will don't break

**Comment by d7prog** [comment]
Thanks Wyatt59 for your suggestion, delay(200) has been replaced with millis() to avoid interruption when VOL+ VOL- is adjusted. Now it works as expected.
